### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by sasha-s** [gocircuit/circuit#13]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with circuit. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable circuit on @Sourcegraph by going to https://sourcegraph.com/github.com/gocircuit/circuit and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by bzz** [comment]
Sounds great, shall this one be resolved then?

**Comment by petar** [comment]
Yep :)
