### ISSUE TITLE
Go types for circuit channels

### ISSUE THREAD

**Issue by phuquocvn** [gocircuit/circuit#17]
Thanks for the great project! I just started learning how it works. I'm very new to gocircuit, and also to golang in general. For the channel created by circuit, what types can it store? Can it be used to send any go type? It would be extremely helpful if you could include a minimal golang example.

Thanks!

**Comment by maymounkov** [comment]
Circuit channels elements only send blocks of binary byte data. You
can think of the data type as being []byte.

An example of using circuit channels from Go can be found in
tutorial/watchbot-with-chan

(I am working on adding a new documentation site.)

**Comment by phuquocvn** [comment]
Thanks for the reply, and I look forward to the new documentation site.

Regarding the question above, to send more complicated data, I should then just use encoding/gob?

Thanks.

**Comment by maymounkov** [comment]
Yes, you could.

**Comment by phuquocvn** [comment]
Great! Thanks.
