### ISSUE TITLE
Default path in the anchor file system for a circuit server

### ISSUE THREAD

**Issue by phuquocvn** [gocircuit/circuit#18]
When a server is registered to the circuit, its path in the anchor file system is something like /X1234. Is it possible to attach it to something like /custom_name/X1234?

The use case for this is to separate different services using the directory names (e.g. /apiworker/X1234, or /webapp/X1234). On http://gocircuit-org.appspot.com/sumr.html, something like that seems possible. But it looks like that version of circuit is deprecated (?).

Thanks.

**Comment by maymounkov** [comment]
You cannot do

/custom_name/X1234

The path name specifies how to find the resource, so it starts with a host.

You could name it:

/X1234/custom_name

And then find "custom_name"'s parent by listing the contents of / two
subdirectory levels in.

**Comment by phuquocvn** [comment]
Thanks!
