### ISSUE TITLE
Worker Identity mismatch

### ISSUE THREAD

**Issue by michaeljs1990** [gocircuit/circuit#20]
Sorry this is a help request. I was looking through the code and wasn't able to find any relevant documentation on why this is happening. I have a circuit listening on a private IP on AWS since you can't listen on the public one. I then try and access that circuit from my desktop computer for testing which throws the following.

2015/04/21 14:38:37 rejecting 208.103.*.*:52997 due to worker identity mismatch
 
masked the last on purpose.

Thanks,

**Comment by michaeljs1990** [comment]
Tried to dig a little bit more into this. It appears that the client that is trying to connect has this Addr assigned to it [::]:53344.

here is the simple code i'm using for testing

```
package main

import (
	"flag"
	"fmt"
	"os"

	"github.com/gocircuit/circuit/client"
)

var flagAddr = flag.String("addr", "", "circuit server address (looks like circuit://...)")

func fatalf(format string, arg ...interface{}) {
	println(fmt.Sprintf(format, arg...))
	os.Exit(1)
}

func connect(addr string) *client.Client {
	defer func() {
		if r := recover(); r != nil {
			fatalf("could not connect: %v", r)
		}
	}()
	return client.Dial(addr, nil)
}

func main() {
	flag.Parse()
	connect(*flagAddr)
}
```

**Comment by michaeljs1990** [comment]
Fixed it. Just set my hosts file to have the private ip point to the public one. This is acceptable to me since this is just for testing. Would you mind if I send you a pull request to fix the output for this error. If the unique path is different it's very clear what is going on but when the IP is different you just get the error above which is a little annoying and made me dig deeper than I wanted to.

**Comment by petar** [comment]
Hi Michael. Yes, absolutely, send a pull request. Before I can do a final commit, please,
take a minute to submit the CLA agreement. This works the same way as the Go Language Individual CLA agreement. Find the form here: http://goo.gl/forms/Qf5V5jTeWa
